"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ProtectedShell } from "../components/auth-ui";
import { AiRunButton, SuggestionPanel } from "../components/ai-ui";
import { ErrorState, StatusBadge } from "../components/business-ui";
import { api, type DailyTop3, type Project, type Suggestion } from "../lib/api";

export default function DashboardPage() { const [daily, setDaily] = useState<DailyTop3 | null>(null); const [projects, setProjects] = useState<Project[]>([]); const [suggestion, setSuggestion] = useState<Suggestion | null>(null); const [error, setError] = useState<unknown>(null); const load = () => { void Promise.all([api.dashboard.dailyTop3(), api.projects.list()]).then(([nextDaily, nextProjects]) => { setDaily(nextDaily); setProjects(nextProjects.projects.slice(0, 3)); if (nextDaily.suggestion?.id) return api.ai.getSuggestion(nextDaily.suggestion.id).then(setSuggestion); return undefined; }).catch(setError); }; useEffect(load, []); return <ProtectedShell><div className="page-header"><div><div className="eyebrow">今天</div><h1>从一个重点开始</h1><p>先推进最重要的事情，再回到项目和客户上下文。</p></div><AiRunButton capability="DAILY_TOP3" onDone={(run) => { const id = run.outputSummary?.suggestionId; if (id) void api.ai.getSuggestion(id).then(setSuggestion).catch(setError); }} /></div>{error ? <ErrorState error={error} /> : <>{suggestion ? <SuggestionPanel suggestion={suggestion} onChanged={(next) => { setSuggestion(next); void load(); }} onClose={() => setSuggestion(null)} /> : null}<section className="panel"><h2>今日三件事</h2>{!daily ? <div className="loading">正在整理今天的重点…</div> : daily.items.length === 0 ? <p className="status">还没有活跃任务。去项目中创建第一个任务。</p> : <div className="task-tree">{daily.items.map((item) => <div className="task-row" key={item.taskId}><div><strong>{item.rank}. {item.title}</strong><div className="status"><StatusBadge value={item.status} />{item.dueAt ? ` · 截止 ${new Date(item.dueAt).toLocaleDateString("zh-CN")}` : ""}</div></div><Link className="text-link" href={`/projects/${item.projectId}`}>查看项目</Link></div>)}</div>}</section><section className="panel"><div className="page-header"><div><h2>活跃项目</h2><p>最多显示三个最近更新的项目。</p></div><Link className="text-link" href="/projects">查看全部</Link></div>{projects.length === 0 ? <p className="status">还没有项目。</p> : projects.map((project) => <div className="task-row" key={project.id}><div><Link className="text-link" href={`/projects/${project.id}`}>{project.name}</Link><div className="status"><StatusBadge value={project.status} /> · {project.taskSummary.completed}/{project.taskSummary.total} 项任务已完成</div></div></div>)}</section></>}</ProtectedShell>; }
