import { randomUUID } from "node:crypto";
import type { Pool, PoolClient } from "pg";
import { appendAuditEvent } from "../platform/audit.js";
import { ApiError } from "../platform/errors.js";
import { recordIdempotent, replayIdempotent, requireUpdatedRow, validateExpectedVersion } from "../platform/concurrency.js";

export interface TaskDeps { pool: Pool; }
type Context = { userId: string; requestId: string; traceId: string };
type TaskStatus = "DRAFT" | "CONFIRMED" | "IN_PROGRESS" | "COMPLETED" | "CLOSED" | "CANCELLED";
type Action = "confirm" | "start" | "complete" | "close" | "cancel" | "defer";
type TaskRow = { id: string; workspace_id: string; project_id: string; parent_task_id: string | null; depth: number; title: string; description: string | null; assignee_user_id: string; status: TaskStatus; due_at: Date | null; estimated_minutes: number | null; is_deferred: boolean; is_overdue: boolean; source: string; source_ai_suggestion_id: string | null; completed_at: Date | null; closed_at: Date | null; cancelled_at: Date | null; created_at: Date; updated_at: Date; version: number };

export interface TaskCreateInput { title: string; description?: string; parentTaskId?: string; dueAt?: string; estimatedMinutes?: number; }
export interface TaskUpdateInput { title?: string; description?: string | null; dueAt?: string | null; estimatedMinutes?: number | null; expectedVersion: number; }

const taskStatuses = new Set<TaskStatus>(["DRAFT", "CONFIRMED", "IN_PROGRESS", "COMPLETED", "CLOSED", "CANCELLED"]);
const terminalStatuses = new Set<TaskStatus>(["COMPLETED", "CLOSED", "CANCELLED"]);

function text(value: string, maximum: number, field: string): string { const normalized = value.trim(); if (!normalized || normalized.length > maximum) throw new ApiError(422, "VALIDATION_FAILED", `${field}长度不符合要求。`); return normalized; }
function optionalText(value: string | null | undefined, maximum: number, field: string): string | null { if (value === undefined || value === null || value === "") return null; return text(value, maximum, field); }
function dueAt(value: string | null | undefined): string | null { if (value === undefined || value === null || value === "") return null; const parsed = new Date(value); if (Number.isNaN(parsed.getTime())) throw new ApiError(422, "VALIDATION_FAILED", "截止时间必须为有效 RFC 3339 时间。 "); return parsed.toISOString(); }
function minutes(value: number | null | undefined): number | null { if (value === undefined || value === null) return null; if (!Number.isInteger(value) || value < 1) throw new ApiError(422, "VALIDATION_FAILED", "预计分钟数必须为正整数。"); return value; }
function response(row: TaskRow) { return { id: row.id, projectId: row.project_id, parentTaskId: row.parent_task_id, depth: Number(row.depth), title: row.title, description: row.description, assigneeUserId: row.assignee_user_id, status: row.status, dueAt: row.due_at?.toISOString() ?? null, estimatedMinutes: row.estimated_minutes, isDeferred: row.is_deferred, isOverdue: row.due_at !== null && row.due_at < new Date() && !terminalStatuses.has(row.status), source: row.source, sourceAiSuggestionId: row.source_ai_suggestion_id, version: row.version, createdAt: row.created_at.toISOString(), updatedAt: row.updated_at.toISOString(), completedAt: row.completed_at?.toISOString() ?? null, closedAt: row.closed_at?.toISOString() ?? null, cancelledAt: row.cancelled_at?.toISOString() ?? null }; }

async function workspaceForRead(connection: Pool | PoolClient, userId: string): Promise<{ id: string; status: string }> { const result = await connection.query<{ id: string; status: string }>("SELECT id, status FROM workspace WHERE owner_user_id=$1", [userId]); if (!result.rows[0]) throw new ApiError(404, "RESOURCE_NOT_FOUND", "当前账户尚未创建工作空间。"); return result.rows[0]; }
async function workspaceForWrite(connection: Pool | PoolClient, userId: string): Promise<string> { const workspace = await workspaceForRead(connection, userId); if (workspace.status !== "ACTIVE") throw new ApiError(403, "WORKSPACE_READ_ONLY", "当前工作空间为只读状态。"); return workspace.id; }
async function projectExists(connection: Pool | PoolClient, workspaceId: string, projectId: string, writable = false): Promise<void> { const result = await connection.query<{ status: string }>("SELECT status FROM project WHERE id=$1 AND workspace_id=$2", [projectId, workspaceId]); if (!result.rows[0]) throw new ApiError(404, "RESOURCE_NOT_FOUND", "当前工作空间中不存在该项目。"); if (writable && ["COMPLETED", "CANCELLED"].includes(result.rows[0].status)) throw new ApiError(409, "INVALID_STATE_TRANSITION", "终态项目不可创建或编辑任务。"); }
async function taskById(connection: Pool | PoolClient, workspaceId: string, taskId: string): Promise<TaskRow | undefined> { return (await connection.query<TaskRow>("SELECT * FROM task WHERE id=$1 AND workspace_id=$2", [taskId, workspaceId])).rows[0]; }
async function taskForProject(connection: Pool | PoolClient, workspaceId: string, projectId: string, taskId: string): Promise<TaskRow | undefined> { return (await connection.query<TaskRow>("SELECT * FROM task WHERE id=$1 AND workspace_id=$2 AND project_id=$3", [taskId, workspaceId, projectId])).rows[0]; }

export async function listTasks(projectId: string, input: { parentTaskId?: string | undefined; status?: string[] | undefined; limit?: number | undefined; cursor?: string | undefined }, context: Context, deps: TaskDeps) {
  const workspaceId = (await workspaceForRead(deps.pool, context.userId)).id; await projectExists(deps.pool, workspaceId, projectId); const limit = input.limit ?? 20;
  if (!Number.isInteger(limit) || limit < 1 || limit > 100) throw new ApiError(422, "VALIDATION_FAILED", "limit 必须为 1 到 100 的整数。"); if ((input.status ?? []).some((status) => !taskStatuses.has(status as TaskStatus))) throw new ApiError(422, "VALIDATION_FAILED", "status 包含不支持的值。");
  const requestedStatuses = input.status ?? []; let cursor: { createdAt: string; id: string; parentTaskId: string | null; status: string[] } | undefined;
  if (input.cursor) { try { cursor = JSON.parse(Buffer.from(input.cursor, "base64url").toString("utf8")) as { createdAt: string; id: string; parentTaskId: string | null; status: string[] }; } catch { throw new ApiError(422, "VALIDATION_FAILED", "cursor 无效。"); } if (!cursor.createdAt || !cursor.id || !Array.isArray(cursor.status) || cursor.parentTaskId !== (input.parentTaskId ?? null) || cursor.status.join("|") !== requestedStatuses.join("|")) throw new ApiError(422, "VALIDATION_FAILED", "cursor 与当前查询条件不匹配。"); }
  const values: unknown[] = [workspaceId, projectId]; const filters = ["workspace_id=$1", "project_id=$2"];
  if (input.parentTaskId !== undefined) { values.push(input.parentTaskId || null); filters.push(`parent_task_id IS NOT DISTINCT FROM $${values.length}::uuid`); }
  if (requestedStatuses.length) { values.push(requestedStatuses); filters.push(`status = ANY($${values.length}::text[])`); }
  if (cursor) { values.push(cursor.createdAt, cursor.id); filters.push(`(created_at, id) > ($${values.length - 1}::timestamptz, $${values.length}::uuid)`); }
  values.push(limit + 1); const result = await deps.pool.query<TaskRow>(`SELECT * FROM task WHERE ${filters.join(" AND ")} ORDER BY created_at ASC, id ASC LIMIT $${values.length}`, values); const page = result.rows.slice(0, limit); const tail = page.at(-1); return { tasks: page.map(response), nextCursor: result.rows.length > limit && tail ? Buffer.from(JSON.stringify({ createdAt: tail.created_at.toISOString(), id: tail.id, parentTaskId: input.parentTaskId ?? null, status: requestedStatuses })).toString("base64url") : null, hasMore: result.rows.length > limit };
}

export async function getTask(taskId: string, context: Context, deps: TaskDeps) { const workspaceId = (await workspaceForRead(deps.pool, context.userId)).id; const row = await taskById(deps.pool, workspaceId, taskId); if (!row) throw new ApiError(404, "RESOURCE_NOT_FOUND", "当前工作空间中不存在该任务。"); return response(row); }

export async function createTask(projectId: string, input: TaskCreateInput, key: string, context: Context, deps: TaskDeps) {
  const normalized = { title: text(input.title, 200, "任务标题"), description: optionalText(input.description, 4000, "任务描述"), parentTaskId: input.parentTaskId ?? null, dueAt: dueAt(input.dueAt), estimatedMinutes: minutes(input.estimatedMinutes) }; const idempotencyInput = { projectId, ...normalized };
  const client = await deps.pool.connect(); try { await client.query("BEGIN"); const previous = await replayIdempotent(client, context, "task.create", key, idempotencyInput); if (previous) { await client.query("COMMIT"); return previous; } const workspaceId = await workspaceForWrite(client, context.userId); await projectExists(client, workspaceId, projectId, true);
    let depth = 1; if (normalized.parentTaskId) { const parent = await taskForProject(client, workspaceId, projectId, normalized.parentTaskId); if (!parent) throw new ApiError(404, "RESOURCE_NOT_FOUND", "当前项目中不存在父任务。"); depth = parent.depth + 1; if (depth > 3) throw new ApiError(422, "TASK_DEPTH_EXCEEDED", "任务最多支持三级层级。"); }
    const id = randomUUID(); await client.query("INSERT INTO task (id,workspace_id,project_id,parent_task_id,depth,title,description,assignee_user_id,due_at,estimated_minutes,created_by_user_id,updated_by_user_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$8,$8)", [id, workspaceId, projectId, normalized.parentTaskId, depth, normalized.title, normalized.description, context.userId, normalized.dueAt, normalized.estimatedMinutes]); const row = await taskById(client, workspaceId, id); if (!row) throw new Error("Task creation was not persisted"); const value = response(row);
    await appendAuditEvent(client, { eventId: randomUUID(), occurredAt: new Date(), actorType: "USER", actorId: context.userId, workspaceId, action: "TASK_CREATED", resourceType: "task", resourceId: id, afterSummary: { status: "DRAFT", depth }, requestId: context.requestId, traceId: context.traceId, result: "SUCCESS" }); await recordIdempotent(client, context, "task.create", key, idempotencyInput, id, value); await client.query("COMMIT"); return value;
  } catch (error) { await client.query("ROLLBACK").catch(() => undefined); throw error; } finally { client.release(); }
}

export async function updateTask(taskId: string, input: TaskUpdateInput, key: string, context: Context, deps: TaskDeps) {
  validateExpectedVersion(input.expectedVersion); const idempotencyInput = { taskId, ...input }; const client = await deps.pool.connect(); try { await client.query("BEGIN"); const previous = await replayIdempotent(client, context, "task.update", key, idempotencyInput); if (previous) { await client.query("COMMIT"); return previous; } const workspaceId = await workspaceForWrite(client, context.userId); const current = await taskById(client, workspaceId, taskId); if (!current) throw new ApiError(404, "RESOURCE_NOT_FOUND", "当前工作空间中不存在该任务。"); await projectExists(client, workspaceId, current.project_id, true); if (["CLOSED", "CANCELLED"].includes(current.status)) throw new ApiError(409, "INVALID_STATE_TRANSITION", "终态任务不可编辑。");
    const title = input.title === undefined ? current.title : text(input.title, 200, "任务标题"); const description = input.description === undefined ? current.description : optionalText(input.description, 4000, "任务描述"); const nextDueAt = input.dueAt === undefined ? current.due_at : dueAt(input.dueAt); const estimate = input.estimatedMinutes === undefined ? current.estimated_minutes : minutes(input.estimatedMinutes);
    const result = await client.query("UPDATE task SET title=$1,description=$2,due_at=$3,estimated_minutes=$4,updated_by_user_id=$5,version=version+1 WHERE id=$6 AND workspace_id=$7 AND version=$8 RETURNING id", [title, description, nextDueAt, estimate, context.userId, taskId, workspaceId, input.expectedVersion]); requireUpdatedRow(result.rows[0]); const row = await taskById(client, workspaceId, taskId); if (!row) throw new Error("Updated task was not found"); const value = response(row);
    await appendAuditEvent(client, { eventId: randomUUID(), occurredAt: new Date(), actorType: "USER", actorId: context.userId, workspaceId, action: "TASK_UPDATED", resourceType: "task", resourceId: taskId, beforeSummary: { status: current.status }, afterSummary: { status: row.status }, requestId: context.requestId, traceId: context.traceId, result: "SUCCESS" }); await recordIdempotent(client, context, "task.update", key, idempotencyInput, taskId, value); await client.query("COMMIT"); return value;
  } catch (error) { await client.query("ROLLBACK").catch(() => undefined); throw error; } finally { client.release(); }
}

export async function transitionTask(taskId: string, action: Action, input: { expectedVersion: number; childTaskHandling?: "CANCEL_ALL"; isDeferred?: boolean }, key: string, context: Context, deps: TaskDeps) {
  validateExpectedVersion(input.expectedVersion); if (!["confirm", "start", "complete", "close", "cancel", "defer"].includes(action)) throw new ApiError(422, "VALIDATION_FAILED", "任务动作无效。"); if (action === "cancel" && input.childTaskHandling !== undefined && input.childTaskHandling !== "CANCEL_ALL") throw new ApiError(422, "VALIDATION_FAILED", "childTaskHandling 无效。"); if (action === "defer" && typeof input.isDeferred !== "boolean") throw new ApiError(422, "VALIDATION_FAILED", "isDeferred 必须为布尔值。");
  const idempotencyInput = { taskId, action, ...input }; const client = await deps.pool.connect(); try { await client.query("BEGIN"); const previous = await replayIdempotent(client, context, `task.${action}`, key, idempotencyInput); if (previous) { await client.query("COMMIT"); return previous; } const workspaceId = await workspaceForWrite(client, context.userId); const current = await taskById(client, workspaceId, taskId); if (!current) throw new ApiError(404, "RESOURCE_NOT_FOUND", "当前工作空间中不存在该任务。"); await projectExists(client, workspaceId, current.project_id, true);
    let next = current.status; let deferred = current.is_deferred; let completed = false; let closed = false; let cancelled = false;
    if (action === "confirm") { if (current.status !== "DRAFT") throw new ApiError(409, "INVALID_STATE_TRANSITION", "仅草稿任务可以确认。"); next = "CONFIRMED"; }
    else if (action === "start") { if (current.status !== "CONFIRMED") throw new ApiError(409, "INVALID_STATE_TRANSITION", "仅已确认任务可以开始。"); next = "IN_PROGRESS"; }
    else if (action === "complete") { if (current.status !== "IN_PROGRESS") throw new ApiError(409, "INVALID_STATE_TRANSITION", "仅进行中任务可以完成。"); next = "COMPLETED"; completed = true; }
    else if (action === "close") { if (current.status !== "COMPLETED") throw new ApiError(409, "INVALID_STATE_TRANSITION", "仅已完成任务可以关闭。"); next = "CLOSED"; closed = true; }
    else if (action === "defer") { if (current.status !== "IN_PROGRESS") throw new ApiError(409, "INVALID_STATE_TRANSITION", "仅进行中任务可以标记延期。"); deferred = input.isDeferred!; }
    else { if (!(["DRAFT", "CONFIRMED", "IN_PROGRESS"] as TaskStatus[]).includes(current.status)) throw new ApiError(409, "INVALID_STATE_TRANSITION", "当前任务状态不可取消。"); const descendants = await client.query<{ count: number }>("WITH RECURSIVE descendants AS (SELECT id,status FROM task WHERE parent_task_id=$1 AND workspace_id=$2 AND project_id=$3 UNION ALL SELECT child.id,child.status FROM task child JOIN descendants parent ON child.parent_task_id=parent.id WHERE child.workspace_id=$2 AND child.project_id=$3) SELECT count(*) FILTER (WHERE status NOT IN ('COMPLETED','CLOSED','CANCELLED'))::int AS count FROM descendants", [taskId, workspaceId, current.project_id]); if ((descendants.rows[0]?.count ?? 0) > 0 && input.childTaskHandling !== "CANCEL_ALL") throw new ApiError(422, "VALIDATION_FAILED", "存在未终态子任务，请先处理或使用 CANCEL_ALL。"); if (input.childTaskHandling === "CANCEL_ALL") await client.query("WITH RECURSIVE descendants AS (SELECT id FROM task WHERE parent_task_id=$1 AND workspace_id=$2 AND project_id=$3 UNION ALL SELECT child.id FROM task child JOIN descendants parent ON child.parent_task_id=parent.id WHERE child.workspace_id=$2 AND child.project_id=$3) UPDATE task SET status='CANCELLED',cancelled_at=now(),updated_by_user_id=$4,version=version+1 WHERE id IN (SELECT id FROM descendants) AND status NOT IN ('COMPLETED','CLOSED','CANCELLED')", [taskId, workspaceId, current.project_id, context.userId]); next = "CANCELLED"; cancelled = true; }
    const result = await client.query("UPDATE task SET status=$1,is_deferred=$2,completed_at=CASE WHEN $3 THEN now() ELSE completed_at END,closed_at=CASE WHEN $4 THEN now() ELSE closed_at END,cancelled_at=CASE WHEN $5 THEN now() ELSE cancelled_at END,updated_by_user_id=$6,version=version+1 WHERE id=$7 AND workspace_id=$8 AND version=$9 RETURNING id", [next, deferred, completed, closed, cancelled, context.userId, taskId, workspaceId, input.expectedVersion]); requireUpdatedRow(result.rows[0]); const row = await taskById(client, workspaceId, taskId); if (!row) throw new Error("Transitioned task was not found"); const value = response(row); const auditAction = { confirm: "TASK_CONFIRMED", start: "TASK_STARTED", complete: "TASK_COMPLETED", close: "TASK_CLOSED", cancel: "TASK_CANCELLED", defer: "TASK_DEFERRED" }[action];
    await appendAuditEvent(client, { eventId: randomUUID(), occurredAt: new Date(), actorType: "USER", actorId: context.userId, workspaceId, action: auditAction, resourceType: "task", resourceId: taskId, beforeSummary: { status: current.status }, afterSummary: { status: next, isDeferred: deferred }, requestId: context.requestId, traceId: context.traceId, result: "SUCCESS" }); await recordIdempotent(client, context, `task.${action}`, key, idempotencyInput, taskId, value); await client.query("COMMIT"); return value;
  } catch (error) { await client.query("ROLLBACK").catch(() => undefined); throw error; } finally { client.release(); }
}
