"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { ProtectedShell } from "../../components/auth-ui";
import { AiRunButton, SuggestionPanel } from "../../components/ai-ui";
import { ErrorState, ProjectForm, StatusBadge, TaskForm, TaskTree } from "../../components/business-ui";
import { api, type AiRun, type Project, type Suggestion, type Task } from "../../lib/api";

export default function ProjectDetailPage() {
  const { projectId } = useParams<{ projectId: string }>();
  const [project, setProject] = useState<Project | null>(null); const [tasks, setTasks] = useState<Task[]>([]); const [suggestion, setSuggestion] = useState<Suggestion | null>(null); const [error, setError] = useState<unknown>(null); const [editing, setEditing] = useState(false); const [creatingTask, setCreatingTask] = useState(false);
  const load = async () => { setError(null); try { const [nextProject, nextTasks] = await Promise.all([api.projects.get(projectId), api.tasks.list(projectId)]); setProject(nextProject); setTasks(nextTasks.tasks); } catch (nextError) { setError(nextError); } };
  useEffect(() => { void load(); }, [projectId]);
  async function action(actionName: Parameters<typeof api.projects.action>[1]) { if (!project) return; try { setProject(await api.projects.action(project.id, actionName, project.version, actionName === "cancel" ? "CANCEL_ALL" : undefined)); await load(); } catch (nextError) { setError(nextError); } }
  async function openSuggestion(run: AiRun) { const suggestionId = run.outputSummary?.suggestionId; if (!suggestionId) return; try { setSuggestion(await api.ai.getSuggestion(suggestionId)); } catch (nextError) { setError(nextError); } }
  return <ProtectedShell><div className="page-header"><div><Link className="text-link" href="/projects">返回项目</Link><h1>{project?.name ?? "项目详情"}</h1><p>{project?.objective ?? "正在加载项目…"}</p></div>{project ? <StatusBadge value={project.status} /> : null}</div>{error ? <ErrorState error={error} retry={() => void load()} /> : null}{project ? <><section className="panel"><div className="page-header"><div><h2>项目摘要</h2><p>状态：<StatusBadge value={project.status} /> · 任务 {project.taskSummary.completed}/{project.taskSummary.total} 已完成</p></div><div className="inline-actions"><AiRunButton capability="TASK_BREAKDOWN" projectId={project.id} disabled={["COMPLETED", "CANCELLED"].includes(project.status)} onDone={(run) => void openSuggestion(run)} />{["DRAFT", "IN_PROGRESS", "PAUSED"].includes(project.status) ? <button className="button button-secondary" onClick={() => setEditing((value) => !value)}>编辑</button> : null}{project.status === "DRAFT" ? <button className="button button-primary" onClick={() => void action("start")}>开始</button> : null}{project.status === "IN_PROGRESS" ? <button className="button button-secondary" onClick={() => void action("pause")}>暂停</button> : null}{project.status === "PAUSED" ? <button className="button button-primary" onClick={() => void action("resume")}>恢复</button> : null}{["DRAFT", "IN_PROGRESS", "PAUSED"].includes(project.status) ? <button className="button button-secondary" onClick={() => void action("cancel")}>取消项目</button> : null}</div></div>{editing ? <ProjectForm initial={project} onDone={(next) => { setProject(next); setEditing(false); }} onCancel={() => setEditing(false)} /> : null}</section>{suggestion ? <SuggestionPanel suggestion={suggestion} onChanged={(next) => { setSuggestion(next); void load(); }} onClose={() => setSuggestion(null)} /> : null}<section className="panel"><div className="page-header"><div><h2>任务树</h2><p>最多三级；确认前任务不会进入执行状态。</p></div><button className="button button-primary" disabled={["COMPLETED", "CANCELLED"].includes(project.status)} onClick={() => setCreatingTask((value) => !value)}>新建任务</button></div>{creatingTask ? <TaskForm projectId={project.id} onDone={(task) => { setTasks((current) => [...current, task]); setCreatingTask(false); }} onCancel={() => setCreatingTask(false)} /> : null}<TaskTree tasks={tasks} projectId={project.id} onChange={() => void load()} /></section></> : null}</ProtectedShell>;
}
