import { randomUUID } from "node:crypto";
import type { Pool } from "pg";
import { appendAuditEvent } from "../platform/audit.js";
import { recordIdempotent, replayIdempotent, validateExpectedVersion } from "../platform/concurrency.js";
import { ApiError } from "../platform/errors.js";

type Context = { userId: string; sessionId: string; requestId: string; traceId: string };
type Deps = { pool: Pool };
type RequestRow = { id: string; status: string; requested_at: Date; grace_ends_at: Date; revoked_at: Date | null; retention_hold: boolean; retention_reason: string | null; retention_expected_end_at: Date | null; tombstoned_at: Date | null; version: number };
const fields = "id,status,requested_at,grace_ends_at,revoked_at,retention_hold,retention_reason,retention_expected_end_at,tombstoned_at,version";
function response(row: RequestRow) { return { id: row.id, status: row.status, requestedAt: row.requested_at.toISOString(), graceEndsAt: row.grace_ends_at.toISOString(), revokedAt: row.revoked_at?.toISOString() ?? null, retentionHold: row.retention_hold, retentionReason: row.retention_reason, retentionExpectedEndAt: row.retention_expected_end_at?.toISOString() ?? null, tombstonedAt: row.tombstoned_at?.toISOString() ?? null, version: row.version }; }
async function activeContext(pool: Pool, context: Context) { const state = await pool.query<{ workspace_id: string; user_status: string; workspace_status: string; last_authenticated_at: Date | null }>("SELECT w.id AS workspace_id,u.status AS user_status,w.status AS workspace_status,s.last_authenticated_at FROM app_user u JOIN workspace w ON w.owner_user_id=u.id JOIN session s ON s.id=$2 AND s.user_id=u.id AND s.revoked_at IS NULL WHERE u.id=$1 FOR UPDATE", [context.userId, context.sessionId]); const row = state.rows[0]; if (!row) throw new ApiError(401, "UNAUTHENTICATED", "当前会话已失效。"); return row; }
function requireRecentReauth(value: Date | null): void { if (!value || value.getTime() + 15 * 60 * 1000 <= Date.now()) throw new ApiError(422, "REAUTH_REQUIRED", "该操作需要在当前会话中重新验证身份。"); }
export async function requestDeactivation(input: { reason?: string }, key: string, context: Context, deps: Deps) { if (input.reason !== undefined && (input.reason.trim().length === 0 || input.reason.length > 500)) throw new ApiError(422, "VALIDATION_FAILED", "注销原因长度不符合要求。"); const client = await deps.pool.connect(); try { await client.query("BEGIN"); const replay = await replayIdempotent<ReturnType<typeof response>>(client, context, "deactivation.request", key, input); if (replay) { await client.query("COMMIT"); return replay; } const state = await activeContext(client as unknown as Pool, context); requireRecentReauth(state.last_authenticated_at); if (state.user_status !== "ACTIVE" || state.workspace_status !== "ACTIVE") throw new ApiError(409, "INVALID_STATE_TRANSITION", "当前账户不能申请注销。"); const id = randomUUID(); const row = (await client.query<RequestRow>(`INSERT INTO deactivation_request (id,user_id,workspace_id,status,grace_ends_at,reason) VALUES ($1,$2,$3,'GRACE',now()+interval '30 days',$4) RETURNING ${fields}`, [id, context.userId, state.workspace_id, input.reason?.trim() ?? null])).rows[0]!; await client.query("UPDATE app_user SET status='DEACTIVATION_GRACE',version=version+1 WHERE id=$1", [context.userId]); await client.query("UPDATE workspace SET status='READ_ONLY',version=version+1 WHERE id=$1", [state.workspace_id]); await client.query("UPDATE session SET revoked_at=now(),revoke_reason='DEACTIVATED' WHERE user_id=$1 AND id<>$2 AND revoked_at IS NULL", [context.userId, context.sessionId]); await client.query("INSERT INTO async_job (id,job_type,status,resource_type,resource_id,workspace_id,trace_id,idempotency_key,run_after) VALUES ($1,'DEACTIVATION_FINALIZE','QUEUED','deactivation_request',$1,$2,$3,$4,now()+interval '30 days')", [id, state.workspace_id, context.traceId, `deactivation-finalize:${id}`]); await appendAuditEvent(client, { eventId: randomUUID(), occurredAt: new Date(), actorType: "USER", actorId: context.userId, workspaceId: state.workspace_id, action: "DEACTIVATION_REQUESTED", resourceType: "DEACTIVATION_REQUEST", resourceId: id, afterSummary: { status: "GRACE" }, requestId: context.requestId, traceId: context.traceId, result: "SUCCESS" }); const body = response(row); await recordIdempotent(client, context, "deactivation.request", key, input, id, body); await client.query("COMMIT"); return body; } catch (error) { await client.query("ROLLBACK").catch(() => undefined); throw error; } finally { client.release(); } }
export async function getDeactivation(context: Context, deps: Deps) { const result = await deps.pool.query<RequestRow>(`SELECT ${fields} FROM deactivation_request WHERE user_id=$1 ORDER BY requested_at DESC LIMIT 1`, [context.userId]); const row = result.rows[0]; if (!row) throw new ApiError(404, "RESOURCE_NOT_FOUND", "未找到注销申请。"); return response(row); }
export async function revokeDeactivation(expectedVersion: number, key: string, context: Context, deps: Deps) { validateExpectedVersion(expectedVersion); const client = await deps.pool.connect(); try { await client.query("BEGIN"); const input = { expectedVersion }; const replay = await replayIdempotent<ReturnType<typeof response>>(client, context, "deactivation.revoke", key, input); if (replay) { await client.query("COMMIT"); return replay; } const state = await activeContext(client as unknown as Pool, context); requireRecentReauth(state.last_authenticated_at); const row = (await client.query<RequestRow>(`SELECT ${fields} FROM deactivation_request WHERE user_id=$1 AND status='GRACE' FOR UPDATE`, [context.userId])).rows[0]; if (!row) throw new ApiError(409, "INVALID_STATE_TRANSITION", "当前注销申请不可撤销。"); if (row.version !== expectedVersion) throw new ApiError(409, "RESOURCE_VERSION_CONFLICT", "数据已被更新，请刷新后重试。"); const updated = (await client.query<RequestRow>(`UPDATE deactivation_request SET status='REVOKED',revoked_at=now(),version=version+1 WHERE id=$1 RETURNING ${fields}`, [row.id])).rows[0]!; await client.query("UPDATE app_user SET status='ACTIVE',version=version+1 WHERE id=$1", [context.userId]); await client.query("UPDATE workspace SET status='ACTIVE',version=version+1 WHERE id=$1", [state.workspace_id]); await client.query("UPDATE async_job SET status='CANCELLED',finished_at=now() WHERE resource_id=$1 AND job_type='DEACTIVATION_FINALIZE' AND status IN ('QUEUED','RETRY_SCHEDULED')", [row.id]); await appendAuditEvent(client, { eventId: randomUUID(), occurredAt: new Date(), actorType: "USER", actorId: context.userId, workspaceId: state.workspace_id, action: "DEACTIVATION_REVOKED", resourceType: "DEACTIVATION_REQUEST", resourceId: row.id, afterSummary: { status: "REVOKED" }, requestId: context.requestId, traceId: context.traceId, result: "SUCCESS" }); const body = response(updated); await recordIdempotent(client, context, "deactivation.revoke", key, input, row.id, body); await client.query("COMMIT"); return body; } catch (error) { await client.query("ROLLBACK").catch(() => undefined); throw error; } finally { client.release(); } }
