"use client";
import { useState } from "react";
import { api, WebApiError, type AiRun, type Suggestion, type SuggestionItem } from "../lib/api";

function errorText(error: unknown) { return error instanceof WebApiError ? error.message : "AI 暂时不可用，请使用手动经营路径。"; }
export function AiRunButton({ capability, projectId, onDone, disabled }: { capability: "TASK_BREAKDOWN" | "DAILY_TOP3"; projectId?: string; onDone: (run: AiRun, events: string[]) => void; disabled?: boolean }) { const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); async function start() { setBusy(true); setMessage("正在准备你的经营信息…"); const events: string[] = []; try { const run = await api.ai.run({ capability, ...(projectId ? { projectId } : {}) }, (event) => { events.push(event.event); if (event.event === "run.progress") setMessage("正在整理项目目标和经营上下文…"); if (event.event === "run.degraded") setMessage("未能生成结构化建议，已保留手动路径。"); if (event.event === "run.failed") setMessage("AI COO 暂时不可用。"); }); onDone(run, events); } catch (error) { setMessage(errorText(error)); } finally { setBusy(false); } } return <div className="inline-actions"><button className="button button-secondary" disabled={disabled || busy} onClick={() => void start()}>{busy ? "生成中…" : capability === "DAILY_TOP3" ? "生成今日建议" : "请 AI 拆解任务"}</button>{message ? <span className="status" aria-live="polite">{message}</span> : null}</div>; }

export function SuggestionPanel({ suggestion, onChanged, onClose }: { suggestion: Suggestion; onChanged: (suggestion: Suggestion) => void; onClose?: () => void }) { const sourceItems = suggestion.proposedPayload.items ?? []; const [items, setItems] = useState<SuggestionItem[]>(sourceItems); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const actionable = suggestion.status === "GENERATED" || suggestion.status === "WAITING_CONFIRMATION"; const isTaskPlan = suggestion.type === "TASK_PLAN";
  async function edit() { setBusy(true); setError(""); try { onChanged(await api.ai.editSuggestion(suggestion.id, { expectedVersion: suggestion.version, items })); } catch (nextError) { setError(errorText(nextError)); } finally { setBusy(false); } }
  async function confirm() { setBusy(true); setError(""); try { const next = isTaskPlan ? await api.ai.confirmSuggestion(suggestion.id, { expectedVersion: suggestion.version, editedPayload: { items } }) : await api.dashboard.confirmTop3({ suggestionId: suggestion.id, expectedVersion: suggestion.version, items: items.map((item, index) => ({ taskId: item.taskId ?? "", rank: index + 1 })) }); onChanged(next); } catch (nextError) { setError(errorText(nextError)); } finally { setBusy(false); } }
  async function reject() { setBusy(true); setError(""); try { onChanged(await api.ai.rejectSuggestion(suggestion.id, { expectedVersion: suggestion.version })); } catch (nextError) { setError(errorText(nextError)); } finally { setBusy(false); } }
  const canProcess = actionable && (suggestion.type === "TASK_PLAN" || suggestion.type === "DAILY_TOP3");
  return <section className="panel"><div className="page-header"><div><div className="eyebrow">AI COO 建议</div><h2>{isTaskPlan ? "任务拆解建议" : "每日三件事建议"}</h2><p>建议状态：{suggestion.status}。AI 不会在确认前创建或修改任务。</p></div>{onClose ? <button className="button button-secondary" onClick={onClose}>关闭</button> : null}</div>{suggestion.proposedPayload.message ? <p className="error-box">{suggestion.proposedPayload.message}</p> : null}{suggestion.proposedPayload.question ? <p className="success-box">需要补充：{suggestion.proposedPayload.question}</p> : null}{isTaskPlan && sourceItems.length ? <div className="form-stack">{items.map((item, index) => <div className="panel" key={item.itemKey ?? item.taskId ?? index}><div className="field"><label htmlFor={`ai-title-${index}`}>任务 {index + 1} 标题</label><input id={`ai-title-${index}`} value={item.title ?? ""} disabled={!actionable} onChange={(event) => setItems((current) => current.map((entry, position) => position === index ? { ...entry, title: event.target.value } : entry))} /></div><div className="field"><label htmlFor={`ai-description-${index}`}>描述</label><textarea id={`ai-description-${index}`} value={item.description ?? ""} disabled={!actionable} onChange={(event) => setItems((current) => current.map((entry, position) => position === index ? { ...entry, description: event.target.value } : entry))} /></div><div className="status">{item.estimatedMinutes ? `预计 ${item.estimatedMinutes} 分钟` : "预计工时待确认"}{item.dueAt ? ` · 截止 ${new Date(item.dueAt).toLocaleDateString("zh-CN")}` : ""}</div></div>)}</div> : null}{!isTaskPlan && sourceItems.length ? <div className="task-tree">{items.map((item, index) => <div className="task-row" key={item.taskId ?? index}><strong>{index + 1}. {item.title ?? item.taskId}</strong><div className="status">{item.reason}</div></div>)}</div> : null}{error ? <div className="error-box" role="alert">{error}</div> : null}{suggestion.status === "DEGRADED" ? <p className="success-box">这是参考性建议，请手动创建任务，不提供一键写入。</p> : null}{suggestion.status === "CONFIRMED" ? <p className="success-box">建议已确认。{suggestion.createdResources.length} 项资源已创建或更新。</p> : null}{canProcess ? <div className="inline-actions">{isTaskPlan ? <button className="button button-secondary" disabled={busy} onClick={() => void edit()}>保存编辑</button> : null}<button className="button button-primary" disabled={busy} onClick={() => void confirm()}>{isTaskPlan ? "确认并创建任务" : "确认今日重点"}</button><button className="button button-secondary" disabled={busy} onClick={() => void reject()}>这次不采用</button></div> : null}</section>; }
