"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { api, hasAccessToken, WebApiError } from "../lib/api";
import { recordUser } from "../lib/auth-context";
import { useAuth } from "../lib/auth-context";

function ErrorBox({ error }: { error: unknown }) { return error ? <div className="error-box" role="alert">{error instanceof WebApiError ? error.message : "操作失败，请稍后重试。"}</div> : null; }
export function AuthLayout({ children }: { children: React.ReactNode }) { return <div className="auth-layout"><aside className="auth-aside"><div><div className="eyebrow" style={{ color: "#c8ddcb" }}>OPC AI OS / V1-A</div><h1>把经营重点，变成今天能推进的事。</h1></div><p>先从清晰的工作空间开始。没有 AI 也能完整管理项目、任务与客户。</p></aside><main className="auth-main">{children}</main></div>; }
export function LoginForm() {
  const [identifier, setIdentifier] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState<unknown>(null); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(null); try { const result = await api.login({ identifier, password }); recordUser(result.user); window.location.href = result.user.status === "ACTIVE" ? "/dashboard" : "/auth/login"; } catch (nextError) { setError(nextError); } finally { setBusy(false); } }
  return <AuthLayout><section className="form-card"><div className="eyebrow">欢迎回来</div><h2>登录你的工作台</h2><p>登录后我们会根据服务端状态恢复你的引导进度。</p><form className="form-stack" onSubmit={submit}><div className="field"><label htmlFor="identifier">邮箱或手机号</label><input id="identifier" required value={identifier} onChange={(event) => setIdentifier(event.target.value)} autoComplete="username" /></div><div className="field"><label htmlFor="password">密码</label><input id="password" required type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="current-password" /></div><ErrorBox error={error} /><button className="button button-primary" disabled={busy}>{busy ? "正在登录…" : "登录"}</button></form><p>还没有账户？ <Link className="text-link" href="/auth/register">创建账户</Link></p></section></AuthLayout>;
}
export function RegisterForm() {
  const [form, setForm] = useState({ email: "", phone: "", password: "", terms: false }); const [error, setError] = useState<unknown>(null); const [done, setDone] = useState(false); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(null); try { await api.register({ ...(form.email ? { email: form.email } : {}), ...(form.phone ? { phone: form.phone } : {}), password: form.password, termsVersion: "v1.0", privacyVersion: "v1.0" }); setDone(true); } catch (nextError) { setError(nextError); } finally { setBusy(false); } }
  if (done) return <AuthLayout><section className="form-card"><div className="eyebrow">账户已创建</div><h2>现在登录，开始设置</h2><p className="success-box">注册成功。下一步创建工作空间并完成基础画像。</p><Link className="button button-primary" href="/auth/login">前往登录</Link></section></AuthLayout>;
  return <AuthLayout><section className="form-card"><div className="eyebrow">开始使用</div><h2>创建你的账户</h2><p>邮箱或手机号至少填写一项。密码至少 12 个字符。</p><form className="form-stack" onSubmit={submit}><div className="field"><label htmlFor="email">邮箱（可选）</label><input id="email" type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} autoComplete="email" /></div><div className="field"><label htmlFor="phone">手机号（可选，E.164 格式）</label><input id="phone" value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} placeholder="+8613800000000" autoComplete="tel" /></div><div className="field"><label htmlFor="register-password">密码</label><input id="register-password" required minLength={12} type="password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} autoComplete="new-password" /></div><label className="checkbox-row"><input type="checkbox" required checked={form.terms} onChange={(event) => setForm({ ...form, terms: event.target.checked })} />我已阅读并同意服务条款与隐私政策。</label><ErrorBox error={error} /><button className="button button-primary" disabled={busy}>{busy ? "正在创建…" : "创建账户"}</button></form><p>已有账户？ <Link className="text-link" href="/auth/login">直接登录</Link></p></section></AuthLayout>;
}
export function ReauthForm({ onSuccess }: { onSuccess: () => void }) { const [password, setPassword] = useState(""); const [error, setError] = useState<unknown>(null); const [busy, setBusy] = useState(false); async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(null); try { await api.reauthenticate(password); onSuccess(); } catch (nextError) { setError(nextError); } finally { setBusy(false); } } return <form className="form-stack" onSubmit={submit}><div className="field"><label htmlFor="reauth-password">再次输入密码</label><input id="reauth-password" type="password" required value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="current-password" /></div><ErrorBox error={error} /><button className="button button-primary" disabled={busy}>{busy ? "验证中…" : "验证身份"}</button></form>; }
export function ProtectedShell({ children, allowIncomplete = false }: { children: React.ReactNode; allowIncomplete?: boolean }) { const { loading, workspace, profile, signOut } = useAuth(); useEffect(() => { if (!loading ? !hasAccessToken() : null) window.location.href = "/auth/login"; else if (!loading && !workspace ? !allowIncomplete : null) window.location.href = "/onboarding/workspace"; else if (!loading && workspace && !profile ? !allowIncomplete : null) window.location.href = "/onboarding/profile"; }, [loading, workspace, profile, allowIncomplete]); if (loading) return <div className="loading">正在恢复你的工作空间…</div>; if (!hasAccessToken()) return <div className="loading">正在返回登录页…</div>; if (!workspace ? !allowIncomplete : null) return <div className="loading">正在进入引导…</div>; if (workspace && !profile ? !allowIncomplete : null) return <div className="loading">正在进入引导…</div>; const readOnly = workspace?.status === "READ_ONLY"; return <div className="app-frame"><aside className="side-nav"><div className="brand">OPC AI OS</div><nav className="nav-links" aria-label="主导航"><Link href="/dashboard">今天</Link><Link href="/projects">项目</Link><Link href="/customers">客户</Link><Link href="/settings">设置</Link></nav><button className="button button-secondary" onClick={signOut}>退出本机</button></aside><main className="main-content"><div className="content-width">{readOnly ? <div className="error-box" role="status">账户正在注销宽限期。你可以查看、导出或撤销申请；不能新建或修改经营数据。</div> : null}{children}</div></main></div>; }
