"use client";

import { type FormEvent, useMemo, useState } from "react";
import { api, WebApiError, type Customer, type CustomerInput, type Project, type ProjectInput, type Task, type TaskInput } from "../lib/api";

export function ErrorState({ error, retry }: { error: unknown; retry?: () => void }) {
  const message = error instanceof WebApiError ? error.message : "暂时无法读取数据，请稍后重试。";
  return <div className="error-box" role="alert"><div>{message}</div>{retry ? <button className="button button-secondary" style={{ marginTop: ".75rem" }} onClick={retry}>重新加载</button> : null}</div>;
}

export function StatusBadge({ value }: { value: string }) {
  const labels: Record<string, string> = { DRAFT: "草稿", CONFIRMED: "已确认", IN_PROGRESS: "进行中", PAUSED: "已暂停", COMPLETED: "已完成", CLOSED: "已关闭", CANCELLED: "已取消", LEAD: "线索", CONTACTED: "已联系", QUALIFIED: "已验证", WON: "已赢得", LOST: "已失去" };
  return <span className="status"><strong>{labels[value] ?? value}</strong></span>;
}

function useFormError() { const [error, setError] = useState<unknown>(null); return { error, setError, message: error ? "操作失败，请检查提示后重试。" : "" }; }

export function ProjectForm({ initial, onDone, onCancel }: { initial?: Project; onDone: (project: Project) => void; onCancel?: () => void }) {
  const [form, setForm] = useState<ProjectInput>({ name: initial?.name ?? "", objective: initial?.objective ?? "", deliverable: initial?.deliverable ?? "", plannedStartAt: initial?.plannedStartAt ?? "", plannedEndAt: initial?.plannedEndAt ?? "" });
  const [busy, setBusy] = useState(false); const { error, setError, message } = useFormError();
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(null); try { onDone(initial ? await api.projects.update(initial.id, { ...form, expectedVersion: initial.version }) : await api.projects.create(form)); } catch (nextError) { setError(nextError); } finally { setBusy(false); } }
  return <form className="form-stack" onSubmit={submit}><div className="field"><label htmlFor="project-name">项目名称</label><input id="project-name" required maxLength={160} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></div><div className="field"><label htmlFor="project-objective">项目目标</label><textarea id="project-objective" required maxLength={4000} value={form.objective} onChange={(e) => setForm({ ...form, objective: e.target.value })} /></div><div className="field"><label htmlFor="project-deliverable">交付物（可选）</label><textarea id="project-deliverable" maxLength={2000} value={form.deliverable} onChange={(e) => setForm({ ...form, deliverable: e.target.value })} /></div><div className="form-grid"><div className="field"><label htmlFor="project-start">开始日期</label><input id="project-start" type="date" value={form.plannedStartAt} onChange={(e) => setForm({ ...form, plannedStartAt: e.target.value })} /></div><div className="field"><label htmlFor="project-end">结束日期</label><input id="project-end" type="date" value={form.plannedEndAt} onChange={(e) => setForm({ ...form, plannedEndAt: e.target.value })} /></div></div>{message ? <ErrorState error={error} /> : null}<div className="inline-actions"><button className="button button-primary" disabled={busy}>{busy ? "保存中…" : initial ? "保存项目" : "创建项目"}</button>{onCancel ? <button type="button" className="button button-secondary" onClick={onCancel}>取消</button> : null}</div></form>;
}

export function TaskForm({ projectId, initial, parentTaskId, onDone, onCancel }: { projectId: string; initial?: Task; parentTaskId?: string; onDone: (task: Task) => void; onCancel?: () => void }) {
  const [form, setForm] = useState<TaskInput>({ title: initial?.title ?? "", description: initial?.description ?? "", dueAt: initial?.dueAt ? initial.dueAt.slice(0, 16) : "", ...(initial?.estimatedMinutes == null ? {} : { estimatedMinutes: initial.estimatedMinutes }), ...(parentTaskId ? { parentTaskId } : {}) });
  const [busy, setBusy] = useState(false); const { error, setError, message } = useFormError();
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(null); try { const task = initial ? await api.tasks.update(initial.id, { title: form.title, description: form.description ?? null, dueAt: form.dueAt || null, estimatedMinutes: form.estimatedMinutes ?? null, expectedVersion: initial.version }) : await api.tasks.create(projectId, { title: form.title, ...(form.description ? { description: form.description } : {}), ...(form.parentTaskId ? { parentTaskId: form.parentTaskId } : {}), ...(form.dueAt ? { dueAt: new Date(form.dueAt).toISOString() } : {}), ...(form.estimatedMinutes == null ? {} : { estimatedMinutes: form.estimatedMinutes }) }); onDone(task); } catch (nextError) { setError(nextError); } finally { setBusy(false); } }
  return <form className="form-stack" onSubmit={submit}><div className="field"><label htmlFor="task-title">任务标题</label><input id="task-title" required maxLength={200} value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></div><div className="field"><label htmlFor="task-description">描述（可选）</label><textarea id="task-description" maxLength={4000} value={form.description ?? ""} onChange={(e) => setForm({ ...form, description: e.target.value })} /></div><div className="form-grid"><div className="field"><label htmlFor="task-due">截止时间</label><input id="task-due" type="datetime-local" value={form.dueAt ?? ""} onChange={(e) => setForm({ ...form, dueAt: e.target.value })} /></div><div className="field"><label htmlFor="task-estimate">预计分钟数</label><input id="task-estimate" type="number" min="1" value={form.estimatedMinutes ?? ""} onChange={(e) => setForm(e.target.value ? { ...form, estimatedMinutes: Number(e.target.value) } : (({ ...rest }) => rest)(form))} /></div></div>{message ? <ErrorState error={error} /> : null}<div className="inline-actions"><button className="button button-primary" disabled={busy}>{busy ? "保存中…" : initial ? "保存任务" : "创建任务"}</button>{onCancel ? <button type="button" className="button button-secondary" onClick={onCancel}>取消</button> : null}</div></form>;
}

export function CustomerForm({ initial, onDone, onCancel }: { initial?: Customer; onDone: (customer: Customer) => void; onCancel?: () => void }) {
  const [form, setForm] = useState<CustomerInput>({ name: initial?.name ?? "", source: initial?.source ?? "", intentLevel: (initial?.intentLevel as CustomerInput["intentLevel"]) ?? "MEDIUM", nextAction: initial?.nextAction ?? "", notes: initial?.notes ?? "" });
  const [busy, setBusy] = useState(false); const { error, setError, message } = useFormError();
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(null); try { onDone(initial ? await api.customers.update(initial.id, { ...form, expectedVersion: initial.version }) : await api.customers.create(form)); } catch (nextError) { setError(nextError); } finally { setBusy(false); } }
  return <form className="form-stack" onSubmit={submit}><div className="field"><label htmlFor="customer-name">客户名称</label><input id="customer-name" required maxLength={160} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></div><div className="form-grid"><div className="field"><label htmlFor="customer-source">线索来源</label><input id="customer-source" required maxLength={64} value={form.source} onChange={(e) => setForm({ ...form, source: e.target.value })} /></div><div className="field"><label htmlFor="customer-intent">意向度</label><select id="customer-intent" value={form.intentLevel} onChange={(e) => setForm({ ...form, intentLevel: e.target.value as CustomerInput["intentLevel"] })}><option value="LOW">低</option><option value="MEDIUM">中</option><option value="HIGH">高</option></select></div></div><div className="field"><label htmlFor="customer-next">下一步动作</label><textarea id="customer-next" maxLength={1000} value={form.nextAction ?? ""} onChange={(e) => setForm({ ...form, nextAction: e.target.value })} /></div><div className="field"><label htmlFor="customer-notes">备注</label><textarea id="customer-notes" value={form.notes ?? ""} onChange={(e) => setForm({ ...form, notes: e.target.value })} /><small>仅你可见，不会默认发送给 AI COO。</small></div>{message ? <ErrorState error={error} /> : null}<div className="inline-actions"><button className="button button-primary" disabled={busy}>{busy ? "保存中…" : initial ? "保存客户" : "创建客户"}</button>{onCancel ? <button type="button" className="button button-secondary" onClick={onCancel}>取消</button> : null}</div></form>;
}

export function TaskTree({ tasks, projectId, onChange }: { tasks: Task[]; projectId: string; onChange: () => void }) { const [editing, setEditing] = useState<Task | null>(null); const [parent, setParent] = useState<string>(); const grouped = useMemo(() => [...tasks].sort((a, b) => a.createdAt.localeCompare(b.createdAt)), [tasks]); async function action(task: Task, next: "confirm" | "start" | "complete" | "close" | "cancel" | "defer") { try { await api.tasks.action(task.id, next, task.version, next === "cancel" ? { childTaskHandling: "CANCEL_ALL" } : next === "defer" ? { isDeferred: !task.isDeferred } : undefined); onChange(); } catch { onChange(); } } if (editing) return <section className="panel"><h3>编辑任务</h3><TaskForm projectId={projectId} initial={editing} onDone={() => { setEditing(null); onChange(); }} onCancel={() => setEditing(null)} /></section>; return <div className="task-tree">{grouped.length === 0 ? <p className="status">还没有任务。先创建一个根任务。</p> : grouped.map((task) => <div className="task-row" style={{ marginLeft: `${(task.depth - 1) * 1.25}rem` }} key={task.id}><div><strong>{task.title}</strong><div className="status"><StatusBadge value={task.status} />{task.isOverdue ? " · 已逾期" : ""}{task.isDeferred ? " · 已延期" : ""} · {task.source === "MANUAL" ? "手动" : "来自 AI 建议"}</div></div><div className="inline-actions"><button className="button button-secondary" onClick={() => setEditing(task)}>编辑</button>{task.depth < 3 ? <button className="button button-secondary" onClick={() => setParent(task.id)}>添加子任务</button> : null}{task.status === "DRAFT" ? <button className="button button-primary" onClick={() => void action(task, "confirm")}>确认</button> : null}{task.status === "CONFIRMED" ? <button className="button button-primary" onClick={() => void action(task, "start")}>开始</button> : null}{task.status === "IN_PROGRESS" ? <><button className="button button-primary" onClick={() => void action(task, "complete")}>完成</button><button className="button button-secondary" onClick={() => void action(task, "defer")}>{task.isDeferred ? "取消延期" : "延期"}</button></> : null}{task.status === "COMPLETED" ? <button className="button button-secondary" onClick={() => void action(task, "close")}>关闭</button> : null}</div>{parent === task.id ? <TaskForm projectId={projectId} parentTaskId={task.id} onDone={() => { setParent(undefined); onChange(); }} onCancel={() => setParent(undefined)} /> : null}</div>)}</div>; }
