import { randomUUID } from "node:crypto";
import type { Pool, PoolClient } from "pg";
import { appendAuditEvent } from "../platform/audit.js";
import { ApiError } from "../platform/errors.js";
import { recordIdempotent, replayIdempotent, requireUpdatedRow, validateExpectedVersion } from "../platform/concurrency.js";

export interface CustomerDeps { pool: Pool; }
type Context = { userId: string; requestId: string; traceId: string };
type Stage = "LEAD" | "CONTACTED" | "QUALIFIED" | "WON" | "LOST";
type IntentLevel = "LOW" | "MEDIUM" | "HIGH";
type CustomerRow = { id: string; workspace_id: string; name: string; source: string; intent_level: IntentLevel; stage: Stage; next_action: string | null; notes: string | null; created_at: Date; updated_at: Date; version: number };
type HistoryRow = { id: string; customer_id: string; workspace_id: string; from_stage: Stage | null; to_stage: Stage; changed_by_user_id: string; changed_at: Date; reason: string | null };

export interface CustomerCreateInput { name: string; source: string; intentLevel: IntentLevel; nextAction?: string; notes?: string; }
export interface CustomerUpdateInput { name?: string; source?: string; intentLevel?: IntentLevel; nextAction?: string | null; notes?: string | null; expectedVersion: number; }

const stages = new Set<Stage>(["LEAD", "CONTACTED", "QUALIFIED", "WON", "LOST"]);
const intents = new Set<IntentLevel>(["LOW", "MEDIUM", "HIGH"]);
const transitions: Readonly<Record<Stage, readonly Stage[]>> = { LEAD: ["CONTACTED", "LOST"], CONTACTED: ["QUALIFIED", "LOST", "LEAD"], QUALIFIED: ["WON", "LOST", "CONTACTED"], WON: [], LOST: ["LEAD", "CONTACTED"] };

function required(value: string, maximum: number, field: string): string { const normalized = value.trim(); if (!normalized || normalized.length > maximum) throw new ApiError(422, "VALIDATION_FAILED", `${field}长度不符合要求。`); return normalized; }
function optional(value: string | null | undefined, maximum: number, field: string): string | null { if (value === undefined || value === null || value === "") return null; return required(value, maximum, field); }
function customerResponse(row: CustomerRow) { return { id: row.id, name: row.name, source: row.source, intentLevel: row.intent_level, stage: row.stage, nextAction: row.next_action, notes: row.notes, version: row.version, createdAt: row.created_at.toISOString(), updatedAt: row.updated_at.toISOString() }; }
function historyResponse(row: HistoryRow) { return { id: row.id, customerId: row.customer_id, fromStage: row.from_stage, toStage: row.to_stage, changedByUserId: row.changed_by_user_id, changedAt: row.changed_at.toISOString(), reason: row.reason }; }

async function workspaceForRead(connection: Pool | PoolClient, userId: string): Promise<{ id: string; status: string }> { const result = await connection.query<{ id: string; status: string }>("SELECT id,status FROM workspace WHERE owner_user_id=$1", [userId]); if (!result.rows[0]) throw new ApiError(404, "RESOURCE_NOT_FOUND", "当前账户尚未创建工作空间。"); return result.rows[0]; }
async function workspaceForWrite(connection: Pool | PoolClient, userId: string): Promise<string> { const workspace = await workspaceForRead(connection, userId); if (workspace.status !== "ACTIVE") throw new ApiError(403, "WORKSPACE_READ_ONLY", "当前工作空间为只读状态。"); return workspace.id; }
async function customerById(connection: Pool | PoolClient, workspaceId: string, customerId: string): Promise<CustomerRow | undefined> { return (await connection.query<CustomerRow>("SELECT * FROM customer WHERE id=$1 AND workspace_id=$2", [customerId, workspaceId])).rows[0]; }

export async function listCustomers(input: { stage?: string[] | undefined; intentLevel?: string[] | undefined; limit?: number | undefined; cursor?: string | undefined }, context: Context, deps: CustomerDeps) {
  const workspaceId = (await workspaceForRead(deps.pool, context.userId)).id; const limit = input.limit ?? 20; const selectedStages = input.stage ?? []; const selectedIntents = input.intentLevel ?? [];
  if (!Number.isInteger(limit) || limit < 1 || limit > 100) throw new ApiError(422, "VALIDATION_FAILED", "limit 必须为 1 到 100 的整数。"); if (selectedStages.some((stage) => !stages.has(stage as Stage)) || selectedIntents.some((intent) => !intents.has(intent as IntentLevel)) ) throw new ApiError(422, "VALIDATION_FAILED", "筛选条件包含不支持的值。");
  let cursor: { updatedAt: string; id: string; stage: string[]; intentLevel: string[] } | undefined; if (input.cursor) { try { cursor = JSON.parse(Buffer.from(input.cursor, "base64url").toString("utf8")) as { updatedAt: string; id: string; stage: string[]; intentLevel: string[] }; } catch { throw new ApiError(422, "VALIDATION_FAILED", "cursor 无效。"); } if (!cursor.updatedAt || !cursor.id || !Array.isArray(cursor.stage) || !Array.isArray(cursor.intentLevel) || cursor.stage.join("|") !== selectedStages.join("|") || cursor.intentLevel.join("|") !== selectedIntents.join("|")) throw new ApiError(422, "VALIDATION_FAILED", "cursor 与当前查询条件不匹配。"); }
  const values: unknown[] = [workspaceId]; const filters = ["workspace_id=$1"]; if (selectedStages.length) { values.push(selectedStages); filters.push(`stage=ANY($${values.length}::text[])`); } if (selectedIntents.length) { values.push(selectedIntents); filters.push(`intent_level=ANY($${values.length}::text[])`); } if (cursor) { values.push(cursor.updatedAt, cursor.id); filters.push(`(updated_at,id)<($${values.length - 1}::timestamptz,$${values.length}::uuid)`); } values.push(limit + 1);
  const result = await deps.pool.query<CustomerRow>(`SELECT * FROM customer WHERE ${filters.join(" AND ")} ORDER BY updated_at DESC,id DESC LIMIT $${values.length}`, values); const page = result.rows.slice(0, limit); const tail = page.at(-1); return { customers: page.map(customerResponse), nextCursor: result.rows.length > limit && tail ? Buffer.from(JSON.stringify({ updatedAt: tail.updated_at.toISOString(), id: tail.id, stage: selectedStages, intentLevel: selectedIntents })).toString("base64url") : null, hasMore: result.rows.length > limit };
}

export async function getCustomer(customerId: string, context: Context, deps: CustomerDeps) { const workspaceId = (await workspaceForRead(deps.pool, context.userId)).id; const row = await customerById(deps.pool, workspaceId, customerId); if (!row) throw new ApiError(404, "RESOURCE_NOT_FOUND", "当前工作空间中不存在该客户。"); return customerResponse(row); }

export async function createCustomer(input: CustomerCreateInput, idempotencyKey: string, context: Context, deps: CustomerDeps) {
  const normalized = { name: required(input.name, 160, "客户名称"), source: required(input.source, 64, "线索来源"), intentLevel: input.intentLevel, nextAction: optional(input.nextAction, 1000, "下一步动作"), notes: input.notes === undefined || input.notes === "" ? null : input.notes }; if (!intents.has(normalized.intentLevel)) throw new ApiError(422, "VALIDATION_FAILED", "意向度无效。");
  const client = await deps.pool.connect(); try { await client.query("BEGIN"); const previous = await replayIdempotent(client, context, "customer.create", idempotencyKey, normalized); if (previous) { await client.query("COMMIT"); return previous; } const workspaceId = await workspaceForWrite(client, context.userId); const id = randomUUID(); await client.query("INSERT INTO customer (id,workspace_id,name,source,intent_level,next_action,notes,created_by_user_id,updated_by_user_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$8)", [id, workspaceId, normalized.name, normalized.source, normalized.intentLevel, normalized.nextAction, normalized.notes, context.userId]); const row = await customerById(client, workspaceId, id); if (!row) throw new Error("Customer creation was not persisted"); const value = customerResponse(row);
    await appendAuditEvent(client, { eventId: randomUUID(), occurredAt: new Date(), actorType: "USER", actorId: context.userId, workspaceId, action: "CUSTOMER_CREATED", resourceType: "customer", resourceId: id, afterSummary: { stage: "LEAD", intentLevel: normalized.intentLevel }, requestId: context.requestId, traceId: context.traceId, result: "SUCCESS" }); await recordIdempotent(client, context, "customer.create", idempotencyKey, normalized, id, value); await client.query("COMMIT"); return value;
  } catch (error) { await client.query("ROLLBACK").catch(() => undefined); throw error; } finally { client.release(); }
}

export async function updateCustomer(customerId: string, input: CustomerUpdateInput, idempotencyKey: string, context: Context, deps: CustomerDeps) {
  validateExpectedVersion(input.expectedVersion); const idempotencyInput = { customerId, ...input }; const client = await deps.pool.connect(); try { await client.query("BEGIN"); const previous = await replayIdempotent(client, context, "customer.update", idempotencyKey, idempotencyInput); if (previous) { await client.query("COMMIT"); return previous; } const workspaceId = await workspaceForWrite(client, context.userId); const current = await customerById(client, workspaceId, customerId); if (!current) throw new ApiError(404, "RESOURCE_NOT_FOUND", "当前工作空间中不存在该客户。");
    const name = input.name === undefined ? current.name : required(input.name, 160, "客户名称"); const source = input.source === undefined ? current.source : required(input.source, 64, "线索来源"); const intentLevel = input.intentLevel === undefined ? current.intent_level : input.intentLevel; if (!intents.has(intentLevel)) throw new ApiError(422, "VALIDATION_FAILED", "意向度无效。"); const nextAction = input.nextAction === undefined ? current.next_action : optional(input.nextAction, 1000, "下一步动作"); const notes = input.notes === undefined ? current.notes : input.notes === "" ? null : input.notes;
    const result = await client.query("UPDATE customer SET name=$1,source=$2,intent_level=$3,next_action=$4,notes=$5,updated_by_user_id=$6,version=version+1 WHERE id=$7 AND workspace_id=$8 AND version=$9 RETURNING id", [name, source, intentLevel, nextAction, notes, context.userId, customerId, workspaceId, input.expectedVersion]); requireUpdatedRow(result.rows[0]); const row = await customerById(client, workspaceId, customerId); if (!row) throw new Error("Updated customer was not found"); const value = customerResponse(row);
    await appendAuditEvent(client, { eventId: randomUUID(), occurredAt: new Date(), actorType: "USER", actorId: context.userId, workspaceId, action: "CUSTOMER_UPDATED", resourceType: "customer", resourceId: customerId, beforeSummary: { stage: current.stage, intentLevel: current.intent_level }, afterSummary: { stage: row.stage, intentLevel: row.intent_level }, requestId: context.requestId, traceId: context.traceId, result: "SUCCESS" }); await recordIdempotent(client, context, "customer.update", idempotencyKey, idempotencyInput, customerId, value); await client.query("COMMIT"); return value;
  } catch (error) { await client.query("ROLLBACK").catch(() => undefined); throw error; } finally { client.release(); }
}

export async function changeCustomerStage(customerId: string, input: { toStage: string; reason?: string; expectedVersion: number }, idempotencyKey: string, context: Context, deps: CustomerDeps) {
  validateExpectedVersion(input.expectedVersion); if (!stages.has(input.toStage as Stage)) throw new ApiError(422, "VALIDATION_FAILED", "目标阶段无效。"); const toStage = input.toStage as Stage; const reason = optional(input.reason, 500, "阶段变更原因"); const idempotencyInput = { customerId, toStage, reason, expectedVersion: input.expectedVersion };
  const client = await deps.pool.connect(); try { await client.query("BEGIN"); const previous = await replayIdempotent(client, context, "customer.change-stage", idempotencyKey, idempotencyInput); if (previous) { await client.query("COMMIT"); return previous; } const workspaceId = await workspaceForWrite(client, context.userId); const current = await customerById(client, workspaceId, customerId); if (!current) throw new ApiError(404, "RESOURCE_NOT_FOUND", "当前工作空间中不存在该客户。"); if (!transitions[current.stage].includes(toStage)) throw new ApiError(409, "INVALID_STATE_TRANSITION", "当前客户阶段不可执行该变更。"); if (((current.stage === "CONTACTED" && toStage === "LEAD") || current.stage === "LOST") && !reason) throw new ApiError(422, "VALIDATION_FAILED", "回退或重新激活客户时必须填写原因。");
    const result = await client.query("UPDATE customer SET stage=$1,updated_by_user_id=$2,version=version+1 WHERE id=$3 AND workspace_id=$4 AND version=$5 RETURNING id", [toStage, context.userId, customerId, workspaceId, input.expectedVersion]); requireUpdatedRow(result.rows[0]); const historyId = randomUUID(); await client.query("INSERT INTO customer_stage_history (id,customer_id,workspace_id,from_stage,to_stage,changed_by_user_id,reason) VALUES ($1,$2,$3,$4,$5,$6,$7)", [historyId, customerId, workspaceId, current.stage, toStage, context.userId, reason]); const row = await customerById(client, workspaceId, customerId); if (!row) throw new Error("Changed customer was not found"); const value = customerResponse(row);
    await appendAuditEvent(client, { eventId: randomUUID(), occurredAt: new Date(), actorType: "USER", actorId: context.userId, workspaceId, action: "CUSTOMER_STAGE_CHANGED", resourceType: "customer", resourceId: customerId, beforeSummary: { stage: current.stage }, afterSummary: { stage: toStage }, requestId: context.requestId, traceId: context.traceId, result: "SUCCESS" }); await recordIdempotent(client, context, "customer.change-stage", idempotencyKey, idempotencyInput, customerId, value); await client.query("COMMIT"); return value;
  } catch (error) { await client.query("ROLLBACK").catch(() => undefined); throw error; } finally { client.release(); }
}

export async function listCustomerStageHistory(customerId: string, input: { limit?: number | undefined; cursor?: string | undefined }, context: Context, deps: CustomerDeps) {
  const workspaceId = (await workspaceForRead(deps.pool, context.userId)).id; if (!await customerById(deps.pool, workspaceId, customerId)) throw new ApiError(404, "RESOURCE_NOT_FOUND", "当前工作空间中不存在该客户。"); const limit = input.limit ?? 20; if (!Number.isInteger(limit) || limit < 1 || limit > 100) throw new ApiError(422, "VALIDATION_FAILED", "limit 必须为 1 到 100 的整数。"); let cursor: { changedAt: string; id: string } | undefined; if (input.cursor) { try { cursor = JSON.parse(Buffer.from(input.cursor, "base64url").toString("utf8")) as { changedAt: string; id: string }; } catch { throw new ApiError(422, "VALIDATION_FAILED", "cursor 无效。"); } if (!cursor.changedAt || !cursor.id) throw new ApiError(422, "VALIDATION_FAILED", "cursor 无效。"); }
  const values: unknown[] = [customerId, workspaceId]; const filters = ["customer_id=$1", "workspace_id=$2"]; if (cursor) { values.push(cursor.changedAt, cursor.id); filters.push(`(changed_at,id)<($${values.length - 1}::timestamptz,$${values.length}::uuid)`); } values.push(limit + 1); const result = await deps.pool.query<HistoryRow>(`SELECT * FROM customer_stage_history WHERE ${filters.join(" AND ")} ORDER BY changed_at DESC,id DESC LIMIT $${values.length}`, values); const page = result.rows.slice(0, limit); const tail = page.at(-1); return { history: page.map(historyResponse), nextCursor: result.rows.length > limit && tail ? Buffer.from(JSON.stringify({ changedAt: tail.changed_at.toISOString(), id: tail.id })).toString("base64url") : null, hasMore: result.rows.length > limit };
}
